In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df=pd.read_csv('Advertising.csv')
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [3]:
X=df.drop('sales',axis=1)
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [4]:
y=df['sales']
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polyConv=PolynomialFeatures(degree=3,include_bias=False)


In [7]:
polyFeat=polyConv.fit_transform(X)


In [8]:
polyFeat.shape

(200, 19)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(polyFeat, y, test_size=0.3, random_state=101)

In [11]:
X_train.shape

(140, 19)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler=StandardScaler()

In [14]:
scaler.fit(X_train)

StandardScaler()

In [15]:
scaled_X_train=scaler.transform(X_train)

In [16]:
scaled_X_test=scaler.transform(X_test)

In [17]:
scaled_X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [18]:
from sklearn.linear_model import Ridge

In [19]:
ridgeModel=Ridge(alpha=0.1)


In [20]:
ridgeModel.fit(X_train,y_train)

Ridge(alpha=0.1)

In [21]:
testPred=ridgeModel.predict(X_test)

In [22]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [23]:
MAE=mean_absolute_error(y_test,testPred)
MAE

0.4127509697741597

In [24]:
MSE=mean_squared_error(y_test,testPred)
RMSE=np.sqrt(MSE)
RMSE

0.580330666875332

In [25]:
 from sklearn.linear_model import RidgeCV

In [26]:
ridge_cv_model=RidgeCV(alphas=(0.1,1,10),scoring='neg_mean_squared_error')

In [27]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 1, 10), scoring='neg_mean_squared_error')

In [28]:
ridge_cv_model.alpha_

10.0

In [29]:
from sklearn.metrics import SCORERS

In [30]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [31]:
ridgeModel.coef_

array([ 8.53137590e-02,  3.15296494e-02,  1.23466962e-02, -4.07702544e-04,
        1.54693686e-03, -3.34550239e-04, -1.79336815e-03,  8.77772393e-04,
        2.55737960e-04,  6.98701284e-07, -1.77805960e-06,  1.07085013e-06,
        2.65938471e-06, -1.70615065e-06,  2.83335998e-08,  2.22483572e-05,
       -8.29346325e-06, -3.65380632e-06, -1.92237670e-06])

In [32]:
ridge_cv_model.best_score_

-0.35348957870389147

In [33]:
from sklearn.linear_model import LassoCV

In [58]:
lassoCV=LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=1000000)

In [59]:
lassoCV.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [60]:
lassoCV.alpha_

23954.310622080106

In [44]:
test_pred=lassoCV.predict(X_test)

In [45]:
MAE=mean_absolute_error(y_test,test_pred)
MAE

1.3018706584630586

In [46]:
MSE=mean_squared_error(y_test,test_pred)
RMSE=np.sqrt(MSE)
RMSE

1.8669834828373244

In [47]:
lassoCV.coef_

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  9.58795042e-08,  3.47802818e-06, -2.10588790e-07,
        1.06879921e-05,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [48]:
from sklearn.linear_model import ElasticNetCV

In [50]:
elasticModel=ElasticNetCV(l1_ratio=[.1, .5, .7,
    .9, .95, .99, 1], eps=0.001,n_alphas=100,max_iter=100000)

In [65]:
elasticModel.fit(scaled_X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000)

In [66]:
elasticModel.l1_ratio_

1.0

In [67]:
elasticModel.alpha_

0.004943070909225832

In [61]:
lassoCV.alpha_

23954.310622080106

In [68]:
test_pred=elasticModel.predict(scaled_X_test)

In [69]:
MAE=mean_absolute_error(y_test,test_pred)
MAE

0.43350346185900696

In [70]:
MSE=mean_squared_error(y_test,test_pred)
RMSE=np.sqrt(MSE)
RMSE

0.6063140748984034