In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
TRAINING_DATA_FILE='../jupyter/environment/SpamData/02_Training/train-data.txt'
TEST_DATA_FILE='../jupyter/environment/SpamData/02_Training/test-data.txt'
VOCAB_SIZE=2500

In [35]:
sparse_train_data=np.loadtxt(TRAINING_DATA_FILE,delimiter=' ', dtype=int)

In [36]:
(sparse_train_data[:,2]==1).sum()

101898

In [37]:
sparse_test_data=np.loadtxt(TEST_DATA_FILE,delimiter=' ', dtype=int)

In [38]:
sparse_test_data

array([[   8,    7,    1,    1],
       [   8,    8,    1,    1],
       [   8,   12,    1,    1],
       ...,
       [5793, 1124,    0,    1],
       [5793, 1261,    0,    1],
       [5793, 2009,    0,    1]])

In [39]:
data_train=pd.DataFrame(sparse_train_data,index=sparse_train_data[:,0])

In [40]:
sparse_train_data.shape

(265427, 4)

In [41]:
sparse_test_data.shape

(110522, 4)

In [42]:
np.unique(sparse_train_data[:,1]).size


2500

In [43]:
np.unique(sparse_test_data[:,1]).size


2490

In [44]:
data_train.set_index(0,inplace=True)

In [45]:
data_train.rename({1:'doc_id', 2:'word_id',3:'label',4:'occurance'},axis=1,inplace=True)


In [46]:
data_train.index.name='x'

In [47]:
# data_train.set_index('doc_id',inplace=True)
data_train.groupby(['doc_id']).count()

word_id  label
doc_id                
0          3090   3090
1          1527   1527
2          2038   2038
3          1260   1260
4          1459   1459
...         ...    ...
2495         25     25
2496         18     18
2497          1      1
2498         15     15
2499         30     30

[2500 rows x 2 columns]

In [48]:
data_test=pd.DataFrame(sparse_test_data)

In [49]:
data_test

0     1  2  3
0          8     7  1  1
1          8     8  1  1
2          8    12  1  1
3          8    19  1  2
4          8    26  1  1
...      ...   ... .. ..
110517  5793   836  0  1
110518  5793  1090  0  1
110519  5793  1124  0  1
110520  5793  1261  0  1
110521  5793  2009  0  1

[110522 rows x 4 columns]

In [50]:
data_test.rename({0:'doc_id', 1:'word_id',2:'label',3:'occurance'},axis=1,inplace=True)


In [51]:
data_test.index.name='x'


In [52]:
data_test.stack(level=0)

x                
0       doc_id          8
        word_id         7
        label           1
        occurance       1
1       doc_id          8
                     ... 
110520  occurance       1
110521  doc_id       5793
        word_id      2009
        label           0
        occurance       1
Length: 442088, dtype: int64

In [53]:
col_names=['doc_id'] + ['label'] + list(range(VOCAB_SIZE))

In [54]:
col_names[:5]

['doc_id', 'label', 0, 1, 2]

In [55]:
index_names=np.unique(sparse_train_data[:,1])

In [56]:
index_names

array([   0,    1,    2, ..., 2497, 2498, 2499])

In [57]:
full_train_data=pd.DataFrame(index=index_names,columns=col_names)

In [58]:
full_train_data

doc_id label    0    1    2    3    4    5    6    7  ... 2490 2491 2492  \
0       NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1       NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2       NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
3       NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
4       NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
...     ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2495    NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2496    NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2497    NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2498    NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
2499    NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   

     2493 2494 2495 2496 2497 2498 2499  
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  
2495  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2496  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2497  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2498  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2499  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[2500 rows x 2502 columns]

In [59]:
full_train_data.fillna(0,inplace=True)

In [60]:
full_train_data

doc_id  label  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0          0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1          0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2          0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3          0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4          0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...      ...    ... .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
2495       0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2496       0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2497       0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2498       0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2499       0      0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
2495     0     0     0     0     0     0  
2496     0     0     0     0     0     0  
2497     0     0     0     0     0     0  
2498     0     0     0     0     0     0  
2499     0     0     0     0     0     0  

[2500 rows x 2502 columns]

In [61]:
# sparse_train_data=sparse_train_data[:,1:]
# sparse_test_data=sparse_test_data[:,1:]


In [62]:
sparse_train_data

array([[   0,    0,    1,    2],
       [   0,    7,    1,    1],
       [   0,   15,    1,    1],
       ...,
       [5795, 1915,    0,    2],
       [5795, 2127,    0,    1],
       [5795, 2279,    0,    1]])

In [63]:
def make_full_matrix(sparse_matrix,nr_words,doc_idx=0,word_idx=1,label_idx=2,freq_idx=3):
    col_names=['doc_id'] + ['label'] + list(range(nr_words))
    index_names=np.unique(sparse_matrix[:,0])
    full_matrix=pd.DataFrame(index=index_names,columns=col_names)
    full_matrix.fillna(0,inplace=True)
    for i in range(sparse_matrix.shape[0]):
        doc_num=sparse_matrix[i][doc_idx]
        word_id=sparse_matrix[i][word_idx]
        label=sparse_matrix[i][label_idx]
        occurence=sparse_matrix[i][freq_idx]
        full_matrix.at[doc_num,'doc_id']=doc_num
        full_matrix.at[doc_num,'label']=label
        full_matrix.at[doc_num,word_id]=occurence
        
    return full_matrix
        
        
    
    
    
    
    
    
    
    
    
    
    
    
    

In [64]:
train_data=make_full_matrix(sparse_train_data,2500)

In [65]:
test_data=make_full_matrix(sparse_test_data,2500)

In [66]:
sparse_test_data

array([[   8,    7,    1,    1],
       [   8,    8,    1,    1],
       [   8,   12,    1,    1],
       ...,
       [5793, 1124,    0,    1],
       [5793, 1261,    0,    1],
       [5793, 2009,    0,    1]])

In [67]:
test_data.set_index('doc_id',inplace=True)

In [68]:
train_data.label.value_counts()

label
0    2765
1    1250
Name: count, dtype: int64

In [69]:
train_data

doc_id  label  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0          0      1  2  0  0  0  0  0  0  1  ...     0     0     0     0   
1          1      1  2  0  1  2  1  1  0  0  ...     0     0     0     0   
2          2      1  2  0  2  0  0  3  0  0  ...     0     0     0     0   
3          3      1  3  0  0  1  0  1  1  0  ...     0     0     0     0   
4          4      1  0  0  0  1  2  4  2  3  ...     0     0     0     0   
...      ...    ... .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5789    5789      0  0  0  0  0  0  5  0  0  ...     0     0     0     0   
5790    5790      0  2  2  1  0  0  0  1  0  ...     0     0     0     0   
5791    5791      0  2  0  1  1  0  1  2  0  ...     0     0     0     0   
5794    5794      0  2  2  1  0  1  1  1  0  ...     0     0     0     0   
5795    5795      0  1  1  1  0  1  1  0  0  ...     0     0     0     0   

      2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
5789     0     0     0     0     0     0  
5790     0     0     0     0     0     0  
5791     0     0     0     0     0     0  
5794     0     0     0     0     0     0  
5795     0     0     0     0     0     0  

[4015 rows x 2502 columns]

In [75]:
p_spam=train_data.label.sum()/len(train_data.label)


In [80]:
train_features=train_data.iloc[:,2:]

In [93]:
total_words=train_features.sum(axis=1).sum()


In [97]:
spam_train_data=train_data[train_data.label==1]
ham_train_data=train_data[train_data.label==0]


In [98]:
spam_features=spam_train_data.iloc[:,2:]
ham_features=ham_train_data.iloc[:,2:]

spam_train_words=spam_features.sum(axis=1).sum()

In [91]:
spam_train_words

195645

In [95]:
ham_words=total_words-spam_train_words

In [99]:
spam_features

0     1     2     3     4     5     6     7     8     9     ...  2490  \
0        2     0     0     0     0     0     0     1     0     0  ...     0   
1        2     0     1     2     1     1     0     0     0     0  ...     0   
2        2     0     2     0     0     3     0     0     0     0  ...     0   
3        3     0     0     1     0     1     1     0     0     0  ...     0   
4        0     0     0     1     2     4     2     3     1     1  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1885     2     0     0     3     2     2     2     2     1     0  ...     0   
1887     0     0     2     2     0     0     0     0     0     0  ...     0   
1889     2     0     1     0     0     4     0     0     0     0  ...     0   
1890     3     0     0     0     0     0     0     1     1     0  ...     0   
1895     0     0     0     0     0     0     0     0     0     0  ...     0   

      2491  2492  2493  2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1885     0     0     0     0     0     0     0     0     0  
1887     0     0     0     0     0     0     0     0     0  
1889     0     0     0     0     0     0     0     0     0  
1890     0     0     0     0     0     0     0     0     0  
1895     0     0     0     0     0     0     0     0     0  

[1250 rows x 2500 columns]

In [113]:
summed_spam_tokens=spam_features.sum(axis=0)
summed_ham_tokens=ham_features.sum(axis=0)


In [104]:
ham_words/len(ham_features)

90.50488245931284

In [105]:
train_features.shape

(4015, 2500)

In [109]:
prob_token_spam=summed_spam_tokens/spam_train_words

In [112]:
prob_token_spam

0       0.009159
1       0.004943
2       0.006921
3       0.010724
4       0.006885
          ...   
2495    0.000092
2496    0.000005
2497    0.000112
2498    0.000046
2499    0.000015
Length: 2500, dtype: float64

In [114]:
prob_token_ham=summed_ham_tokens/ham_words

In [118]:
prob_token_ham

0       0.021067
1       0.009982
2       0.008140
3       0.003768
4       0.006370
          ...   
2495    0.000048
2496    0.000072
2497    0.000000
2498    0.000060
2499    0.000136
Length: 2500, dtype: float64

In [122]:
prob_token_total=train_features.sum(axis=0)/total_words

In [123]:
prob_token_total

0       0.015842
1       0.007771
2       0.007605
3       0.006820
4       0.006596
          ...   
2495    0.000067
2496    0.000043
2497    0.000049
2498    0.000054
2499    0.000083
Length: 2500, dtype: float64

In [126]:
TOKEN_SPAM_PROB='../jupyter/environment/SpamData/03_Testing/prob_spam.txt '
TOKEN_HAM_PROB='../jupyter/environment/SpamData/03_Testing/prob_ham.txt '
TOKEN_TOTAL_PROB='../jupyter/environment/SpamData/03_Testing/prob_total.txt '
TEST_FEATURE_MATRIX='../jupyter/environment/SpamData/03_Testing/test_features.txt'
TEST_TARGET_FILE='../jupyter/environment/SpamData/03_Testing/test_target.txt'

In [125]:
np.savetxt(TOKEN_SPAM_PROB,prob_token_spam)
np.savetxt(TOKEN_HAM_PROB,prob_token_ham)
np.savetxt(TOKEN_TOTAL_PROB,prob_token_total)


In [131]:
X_test=test_data.loc[:,1:]

In [132]:
y_test=test_data.label

In [133]:
np.savetxt(TEST_FEATURE_MATRIX,X_test)
np.savetxt(TEST_TARGET_FILE,y_test)